# Generated by Django 3.2.25 on 2025-04-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250410_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='medical_school',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
